#!/bin/bash

#Getting Metadata Info From The FLACs
for a in ./*.flac; do
  ARTIST=$(metaflac "$a" --show-tag=ARTIST | sed s/.*=//g)
  ALBUM=$(metaflac "$a" --show-tag=ALBUM | sed s/.*=//g)
  DATE=$(metaflac "$a" --show-tag=DATE | sed s/.*=//g)
done
YEAR=$(echo $DATE | awk 'BEGIN {FS="-"}{printf $1}')
DIR=$(pwd)

#Gathering Additional Data From User
read -rp 'Source: ' SOURCE

#Transcoding FLAC->V0
mkdir "/tmp/$ARTIST - $ALBUM - $YEAR [$SOURCE - MP3 - V0]"
flacmpv () {
  f=$1
  flac -cd "$f" | lame -m j -q 0 -V 0 --vbr-new --noreplaygain --ignore-tag-errors --add-id3v2 - /tmp/"${f%.*}".mp3;
}
export -f flacmpv
ls *.flac | time parallel -j+0 --eta flacmpv {}
mv /tmp/*.mp3 "/tmp/$ARTIST - $ALBUM - $YEAR [$SOURCE - MP3 - V0]"
mv "/tmp/$ARTIST - $ALBUM - $YEAR [$SOURCE - MP3 - V0]" $DIR

#Transcoding FLAC->MP3-320
mkdir "/tmp/$ARTIST - $ALBUM - $YEAR [$SOURCE - MP3 - 320]"
flacmpc () {
  a=$1
  flac =cd "$a" | lame -q 0 --cbr -b 320 --noreplaygain --ignore-tag-errors --add-id3v2 - /tmp/"${a%.*}".mp3;
}
export -f flacmpc
ls *.flac | time parallel -j+0 --eta flacmpc {}
mv /tmp/*.mp3 "/tmp/$ARTIST - $ALBUM - $YEAR [$SOURCE - MP3 - 320]"
mv "/tmp/$ARTIST - $ALBUM - $YEAR [$SOURCE - MP3 - 320]" $DIR
